<?php
require_once realpath(dirname(__FILE__)) . '/../TestHelper.php';

class Braintree_ConfigurationTest extends PHPUnit_Framework_TestCase
{

    function testSetValidEnvironment()
    {
        Braintree_Configuration::environment('sandbox');
        $this->assertEquals('sandbox', Braintree_Configuration::environment());
        Braintree_Configuration::reset();
    }

     /**
     * @expectedException Braintree_Exception_Configuration
     * @expectedExceptionMessage environment needs to be set
     */
    function testSetInvalidEnvironment()
    {
        Braintree_Configuration::environment('invalid');
        Braintree_Configuration::reset();
    }

     /**
     * @expectedException Braintree_Exception_Configuration
     * @expectedExceptionMessage environment needs to be set
     */
    function testValidateEmptyEnvironment()
    {
        // try to get environment without setting it first
        Braintree_Configuration::environment();
    }

    /**
     * this tests that the path generated by caFile():
     * is a valid string,
     * contains the appropriate certificate name, and
     * is a file that exists in the filesystem
     */
    function testCAFile()
    {
        // development
        Braintree_Configuration::environment('development');
        $ca = Braintree_Configuration::caFile();
        $this->assertType(PHPUnit_Framework_Constraint_IsType::TYPE_STRING, $ca);
        $this->assertStringEndsWith('valicert_ca.crt', $ca);
        $this->assertFileExists($ca);

        // sandbox
        Braintree_Configuration::environment('sandbox');
        $ca = Braintree_Configuration::caFile();
        $this->assertType(PHPUnit_Framework_Constraint_IsType::TYPE_STRING, $ca);
        $this->assertStringEndsWith('valicert_ca.crt', $ca);
        $this->assertFileExists($ca);

        // qa
        Braintree_Configuration::environment('qa');
        $ca = Braintree_Configuration::caFile();
        $this->assertType(PHPUnit_Framework_Constraint_IsType::TYPE_STRING, $ca);
        $this->assertStringEndsWith('valicert_ca.crt', $ca);
        $this->assertFileExists($ca);

        // production
        Braintree_Configuration::environment('production');
        $ca = Braintree_Configuration::caFile();
        $this->assertType(PHPUnit_Framework_Constraint_IsType::TYPE_STRING, $ca);
        $this->assertStringEndsWith('securetrust_ca.crt', $ca);
        $this->assertFileExists($ca);
        Braintree_Configuration::reset();

    }

    function testMerchantPath()
    {
        Braintree_Configuration::merchantId('abc123');
        $mp = Braintree_Configuration::merchantPath();
        $this->assertEquals('/merchants/abc123', $mp);
        Braintree_Configuration::reset();
    }

    function testSSLOn()
    {
        Braintree_Configuration::environment('development');
        $on = Braintree_Configuration::sslOn();
        $this->assertFalse($on);

        Braintree_Configuration::environment('sandbox');
        $on = Braintree_Configuration::sslOn();
        $this->assertTrue($on);

        Braintree_Configuration::environment('production');
        $on = Braintree_Configuration::sslOn();
        $this->assertTrue($on);

        Braintree_Configuration::reset();
    }
    
    function testPortNumber()
    {
        Braintree_Configuration::environment('development');
        $pn = Braintree_Configuration::portNumber();
        $this->assertEquals(3000, $pn);

        Braintree_Configuration::environment('sandbox');
        $pn = Braintree_Configuration::portNumber();
        $this->assertEquals(443, $pn);
        
        Braintree_Configuration::environment('production');
        $pn = Braintree_Configuration::portNumber();
        $this->assertEquals(443, $pn);

        Braintree_Configuration::reset();
    }


    function testProtocol()
    {
        Braintree_Configuration::environment('development');
        $p = Braintree_Configuration::protocol();
        $this->assertEquals('http', $p);

        Braintree_Configuration::environment('sandbox');
        $p = Braintree_Configuration::protocol();
        $this->assertEquals('https', $p);

        Braintree_Configuration::environment('production');
        $p = Braintree_Configuration::protocol();
        $this->assertEquals('https', $p);

        Braintree_Configuration::reset();
    }

    function testServerName()
    {
        Braintree_Configuration::environment('development');
        $sn = Braintree_Configuration::serverName();
        $this->assertEquals('localhost', $sn);

        Braintree_Configuration::environment('sandbox');
        $sn = Braintree_Configuration::serverName();
        $this->assertEquals('sandbox.braintreegateway.com', $sn);

        Braintree_Configuration::environment('production');
        $sn = Braintree_Configuration::serverName();
        $this->assertEquals('www.braintreegateway.com', $sn);

        Braintree_Configuration::reset();
    }

    function testmerchantUrl()
    {
        Braintree_Configuration::merchantId('abc123');
        Braintree_Configuration::environment('sandbox');
        $mu = Braintree_Configuration::merchantUrl();
        $this->assertEquals('https://sandbox.braintreegateway.com:443/merchants/abc123', $mu);
    
        Braintree_Configuration::reset();
    }

    function testBaseUrl()
    {
        Braintree_Configuration::environment('sandbox');
        $bu = Braintree_Configuration::baseUrl();
        $this->assertEquals('https://sandbox.braintreegateway.com:443', $bu);
    
        Braintree_Configuration::reset();
    }
     /**
     * @expectedException Braintree_Exception_Configuration
     * @expectedExceptionMessage merchantId needs to be set.
     */
    function testMerchantId()
    {
        $mi = Braintree_Configuration::merchantId();
    }
     /**
     * @expectedException Braintree_Exception_Configuration
     * @expectedExceptionMessage publicKey needs to be set.
     */
    function testPublicKey()
    {
        $pk = Braintree_Configuration::publicKey();
    }
     /**
     * @expectedException Braintree_Exception_Configuration
     * @expectedExceptionMessage privateKey needs to be set.
     */
    function testPrivateKey()
    {
        $pk = Braintree_Configuration::privateKey();
    }
}
